-- PDKS için Personel Master View
-- TCKIMLIKNO alanı PDKS_HAMDATA_CACHE tablosundaki SicilNo ile aynı formatta (TURKISH_CI_AS)
-- Filtreleme kriterleri ZU_P_AYARE tablosundan alınır

IF EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VW_PERSM0_PDKS]'))
    DROP VIEW [dbo].[VW_PERSM0_PDKS]
GO

CREATE VIEW [dbo].[VW_PERSM0_PDKS]
AS
SELECT 
    PM0.KOD,
    PM0.AP10,
    PM0.STATU,
    PM0.AD, 
    PM0.SOYAD,
    PM0.AD_SOYAD,
    PM0.TCKIMLIKNO,
    -- TCKIMLIKNO'yu PDKS_HAMDATA_CACHE tablosundaki SicilNo ile aynı formatta (TURKISH_CI_AS) dönüştür
    LTRIM(RTRIM(CAST(PM0.TCKIMLIKNO AS varchar))) COLLATE Turkish_CI_AS AS TCKIMLIKNO_PDKS,
    PM0BT2.HESAPSABLONU,
    PM0.GK_1,
    ZUPAYART1.VARDIYA,
    ZUPAYART1.GIRIS_TOL_DK,
    ZUPAYART1.CIKIS_TOL_DK,
    ZUPAYART1.STIME,
    ZUPAYART1.ETIME,
    ZUPAYART1.TOPLAMSURE_DK,
    ZUPAYART1.TOPLAMSURE_SA,
    PM0.ISEGIRISTARIHI,
    PM0.ISTENCIKISTARIHI
FROM dbo.PERSM0 PM0 WITH (NOLOCK)
CROSS JOIN dbo.ZU_P_AYARE ZUPAYARE WITH (NOLOCK)
LEFT JOIN dbo.PERSM0BT2 PM0BT2 WITH (NOLOCK) 
    ON PM0BT2.KOD = PM0.KOD 
    AND PM0BT2.AP10 = CASE 
        WHEN ZUPAYARE.PM0_AP10 IS NULL OR LTRIM(RTRIM(CAST(ZUPAYARE.PM0_AP10 AS varchar))) = '' 
        THEN PM0.AP10 
        ELSE CAST(ZUPAYARE.PM0_AP10 AS int) 
    END
LEFT JOIN dbo.ZU_P_AYART1 ZUPAYART1 WITH (NOLOCK) 
    ON ZUPAYART1.AP10 = CASE 
        WHEN ZUPAYARE.PM0_AP10 IS NULL OR LTRIM(RTRIM(CAST(ZUPAYARE.PM0_AP10 AS varchar))) = '' 
        THEN PM0.AP10 
        ELSE CAST(ZUPAYARE.PM0_AP10 AS int) 
    END
    AND ZUPAYART1.BEYAZ_MAVI = PM0BT2.HESAPSABLONU
WHERE 1=1
    -- AP10 filtresi: ZU_P_AYARE tablosundan alınır, boş ise tüm kayıtlar
    AND (ZUPAYARE.PM0_AP10 IS NULL OR LTRIM(RTRIM(CAST(ZUPAYARE.PM0_AP10 AS varchar))) = '' OR PM0.AP10 = CAST(ZUPAYARE.PM0_AP10 AS int))
    -- STATU filtresi: ZU_P_AYARE tablosundan alınır, boş ise tüm kayıtlar
    AND (ZUPAYARE.PM0_STATU IS NULL OR LTRIM(RTRIM(CAST(ZUPAYARE.PM0_STATU AS varchar))) = '' OR PM0.STATU = CAST(ZUPAYARE.PM0_STATU AS int))
    -- GK_1 filtresi: ZU_P_AYARE tablosundan alınır, boş ise tüm kayıtlar
    AND (ZUPAYARE.PM0_GK1 IS NULL OR LTRIM(RTRIM(CAST(ZUPAYARE.PM0_GK1 AS varchar))) = '' OR PM0.GK_1 = ZUPAYARE.PM0_GK1)
GO
